### ISSUE TITLE
Kotlin DSL Examples?

### ISSUE THREAD

**Issue by jehugaleahsa** [gradle-guides/building-cpp-executables#3]
Can the equivalent Kotlin DSL examples be provided? Can I use the Kotlin DSL? I have been trying to guess what the syntax would be but I'm too new to Gradle and Kotlin to make any headway.

**Comment by eriwen** [comment]
I'm afraid the deprecated software model used by this guide is not compatible with the Kotlin DSL.

**Comment by jehugaleahsa** [comment]
Thanks for pointing me in that direction. I wasn't aware their was a new model under development.
