### ISSUE TITLE
Typo in header file name

### ISSUE THREAD

**Issue by sharpe-developer** [gradle-guides/building-cpp-executables#5]
In the [Add Source Code](https://guides.gradle.org/building-cpp-executables/#add_source_code) section the text instructs to add an hpp file as shown below. 

> and place a main.cpp and a greeting.hpp within.

All later occurrences of the greetings file use the .h extension and not .hpp. For example:

> #include "greeting.h"

> src/main/cpp/greeting.h

The filename should be consistent

**Comment by lacasseio** [comment]
This will be fixed with the release of 5.5 guide update. Closing now.
